server:
  port: 18080
  contextPath: /mytest

spring:
  datasource:
    url: jdbc:mysql://192.168.1.35:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: stationadmin
    password: station123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
